/**
 * Top ~500 websites for ghost autocomplete in the URL input.
 * Curated for sites that make interesting redesign targets:
 * landing pages, products, portfolios, tools, marketing sites.
 */
export const TOP_SITES: string[] = [
  // Big tech & platforms
  "google.com",
  "youtube.com",
  "facebook.com",
  "instagram.com",
  "twitter.com",
  "x.com",
  "linkedin.com",
  "reddit.com",
  "pinterest.com",
  "tumblr.com",
  "tiktok.com",
  "snapchat.com",
  "discord.com",
  "slack.com",
  "telegram.org",
  "whatsapp.com",
  "signal.org",
  "threads.net",
  "mastodon.social",
  "bluesky.app",

  // E-commerce & retail
  "amazon.com",
  "ebay.com",
  "etsy.com",
  "shopify.com",
  "walmart.com",
  "target.com",
  "bestbuy.com",
  "costco.com",
  "ikea.com",
  "nike.com",
  "adidas.com",
  "zara.com",
  "hm.com",
  "uniqlo.com",
  "asos.com",
  "nordstrom.com",
  "macys.com",
  "wayfair.com",
  "aliexpress.com",
  "wish.com",

  // Tech & SaaS
  "apple.com",
  "microsoft.com",
  "github.com",
  "gitlab.com",
  "vercel.com",
  "netlify.com",
  "cloudflare.com",
  "digitalocean.com",
  "heroku.com",
  "aws.amazon.com",
  "stripe.com",
  "twilio.com",
  "mongodb.com",
  "supabase.com",
  "firebase.google.com",
  "notion.so",
  "figma.com",
  "canva.com",
  "miro.com",
  "airtable.com",
  "zapier.com",
  "hubspot.com",
  "salesforce.com",
  "intercom.com",
  "zendesk.com",
  "mailchimp.com",
  "sendgrid.com",
  "postmark.com",
  "atlassian.com",
  "jira.com",
  "asana.com",
  "trello.com",
  "linear.app",
  "todoist.com",
  "1password.com",
  "bitwarden.com",
  "lastpass.com",
  "dropbox.com",
  "box.com",
  "zoom.us",
  "calendly.com",
  "loom.com",
  "grammarly.com",
  "openai.com",
  "anthropic.com",
  "perplexity.ai",
  "midjourney.com",
  "stability.ai",
  "huggingface.co",
  "replicate.com",
  "cursor.com",
  "replit.com",
  "codepen.io",
  "codesandbox.io",
  "stackblitz.com",
  "glitch.com",
  "railway.app",
  "render.com",
  "fly.io",
  "deno.com",
  "bun.sh",
  "astro.build",
  "nextjs.org",
  "svelte.dev",
  "vuejs.org",
  "angular.io",
  "remix.run",
  "tailwindcss.com",
  "framer.com",
  "webflow.com",
  "squarespace.com",
  "wix.com",
  "wordpress.com",
  "ghost.org",
  "substack.com",
  "medium.com",
  "hashnode.dev",
  "dev.to",

  // Media & entertainment
  "netflix.com",
  "spotify.com",
  "hulu.com",
  "disneyplus.com",
  "hbomax.com",
  "peacocktv.com",
  "paramountplus.com",
  "crunchyroll.com",
  "twitch.tv",
  "soundcloud.com",
  "bandcamp.com",
  "deezer.com",
  "tidal.com",
  "audible.com",
  "kindle.com",

  // News & media
  "nytimes.com",
  "washingtonpost.com",
  "theguardian.com",
  "bbc.com",
  "cnn.com",
  "reuters.com",
  "apnews.com",
  "bloomberg.com",
  "wsj.com",
  "economist.com",
  "wired.com",
  "theverge.com",
  "arstechnica.com",
  "techcrunch.com",
  "engadget.com",
  "mashable.com",
  "vice.com",
  "vox.com",
  "buzzfeed.com",
  "huffpost.com",

  // Design & creative
  "dribbble.com",
  "behance.net",
  "awwwards.com",
  "cssdesignawards.com",
  "siteinspire.com",
  "godly.website",
  "landbook.com",
  "onepagelove.com",
  "typewolf.com",
  "fonts.google.com",
  "fontshare.com",
  "unsplash.com",
  "pexels.com",
  "pixabay.com",
  "coolors.co",
  "colorhunt.co",
  "adobe.com",
  "sketch.com",
  "invisionapp.com",
  "zeplin.io",
  "principle.app",
  "rive.app",
  "spline.design",
  "lottiefiles.com",
  "iconify.design",
  "heroicons.com",
  "lucide.dev",
  "feathericons.com",
  "are.na",
  "read.cv",
  "layers.to",
  "cosmos.so",

  // Fintech & finance
  "stripe.com",
  "paypal.com",
  "venmo.com",
  "cashapp.com",
  "wise.com",
  "revolut.com",
  "monzo.com",
  "chime.com",
  "robinhood.com",
  "coinbase.com",
  "binance.com",
  "kraken.com",
  "plaid.com",
  "brex.com",
  "mercury.com",
  "ramp.com",

  // Travel & hospitality
  "airbnb.com",
  "booking.com",
  "expedia.com",
  "kayak.com",
  "tripadvisor.com",
  "hotels.com",
  "vrbo.com",
  "skyscanner.com",
  "google.com/flights",
  "uber.com",
  "lyft.com",
  "doordash.com",
  "grubhub.com",
  "instacart.com",
  "postmates.com",

  // Health & wellness
  "peloton.com",
  "calm.com",
  "headspace.com",
  "noom.com",
  "myfitnesspal.com",
  "strava.com",
  "whoop.com",
  "oura.com",
  "hims.com",
  "hers.com",
  "ro.co",
  "zocdoc.com",

  // Education
  "coursera.org",
  "udemy.com",
  "edx.org",
  "khanacademy.org",
  "duolingo.com",
  "skillshare.com",
  "masterclass.com",
  "brilliant.org",
  "codecademy.com",
  "freecodecamp.org",
  "leetcode.com",
  "hackerrank.com",

  // Productivity & tools
  "todoist.com",
  "obsidian.md",
  "roamresearch.com",
  "logseq.com",
  "craft.do",
  "bear.app",
  "things3.com",
  "fantastical.app",
  "raycast.com",
  "alfred.app",
  "iterm2.com",
  "warp.dev",
  "arc.net",
  "vivaldi.com",
  "brave.com",
  "opera.com",
  "firefox.com",

  // Consumer brands
  "tesla.com",
  "rivian.com",
  "lucidmotors.com",
  "apple.com",
  "samsung.com",
  "sony.com",
  "bose.com",
  "sonos.com",
  "dyson.com",
  "patagonia.com",
  "allbirds.com",
  "everlane.com",
  "glossier.com",
  "warbyparker.com",
  "casper.com",
  "away.com",
  "peloton.com",
  "lululemon.com",
  "rei.com",
  "northface.com",

  // Interesting / design-forward
  "teenage.engineering",
  "poolside.ai",
  "amie.so",
  "nothing.tech",
  "daylight.computer",
  "once.com",
  "bearblog.dev",
  "ableton.com",
  "rolecatcher.com",
  "pitch.com",
  "superhuman.com",
  "hey.com",
  "basecamp.com",
  "37signals.com",
  "doist.com",
  "panic.com",
  "omnigroup.com",
  "culturedcode.com",
  "flexibits.com",
  "cleanshot.com",
  "pixelmator.com",
  "affinity.serif.com",
  "procreate.com",
  "darkroom.co",
  "halide.cam",
  "overcast.fm",
  "castro.fm",
  "pocketcasts.com",
  "netnewswire.com",
  "reeder.app",
  "carrot.weather",
  "weatherkit.apple.com",

  // Food & drink
  "sweetgreen.com",
  "chipotle.com",
  "starbucks.com",
  "bluebottlecoffee.com",
  "ritual.co",
  "hellofresh.com",
  "blueapron.com",
  "factor75.com",

  // Real estate & home
  "zillow.com",
  "redfin.com",
  "realtor.com",
  "trulia.com",
  "compass.com",
  "houzz.com",

  // Sports & gaming
  "espn.com",
  "nba.com",
  "nfl.com",
  "mlb.com",
  "fifa.com",
  "steam.com",
  "epicgames.com",
  "riotgames.com",
  "playstation.com",
  "xbox.com",
  "nintendo.com",

  // Government & civic
  "usa.gov",
  "whitehouse.gov",
  "nasa.gov",
  "cdc.gov",
  "irs.gov",
  "usps.com",

  // Reference & utility
  "wikipedia.org",
  "archive.org",
  "wolframalpha.com",
  "weather.com",
  "maps.google.com",
  "translate.google.com",
  "speedtest.net",
  "producthunt.com",
  "alternativeto.net",
  "stackexchange.com",
  "stackoverflow.com",
  "quora.com",

  // Misc interesting
  "craigslist.org",
  "ycombinator.com",
  "news.ycombinator.com",
  "indiehackers.com",
  "nomadlist.com",
  "levels.fyi",
  "glassdoor.com",
  "indeed.com",
  "angel.co",
  "wellfound.com",
  "carta.com",
  "gusto.com",
  "rippling.com",
  "deel.com",
  "remote.com",
  "lattice.com",
  "lever.co",
  "greenhouse.io",
  "cal.com",
  "savvycal.com",
  "tally.so",
  "typeform.com",
  "jotform.com",
  "surveymonkey.com",
  "hotjar.com",
  "amplitude.com",
  "mixpanel.com",
  "segment.com",
  "posthog.com",
  "sentry.io",
  "datadog.com",
  "grafana.com",
  "newrelic.com",
  "pagerduty.com",
  "statuspage.io",
  "launchdarkly.com",
  "split.io",
  "optimizely.com",
  "contentful.com",
  "sanity.io",
  "strapi.io",
  "prismic.io",
  "storyblok.com",
  "hygraph.com",
  "payload.cms",
  "builder.io",
  "plasmic.app",
];

/**
 * Find the best autocomplete match for a partial input.
 * Returns the full domain if a match is found, null otherwise.
 */
export function ghostMatch(input: string): string | null {
  if (!input || input.length < 2) return null;
  const lower = input.toLowerCase().trim();
  // Don't suggest if they've already typed a full domain with TLD
  if (/\.\w{2,}$/.test(lower) && TOP_SITES.includes(lower)) return null;
  // Find first match that starts with the input
  return TOP_SITES.find((s) => s.startsWith(lower)) ?? null;
}
