import type { ModelProfile } from "./types";

export const MODELS: ModelProfile[] = [
  {
    id: "claude-sonnet",
    name: "Claude",
    org: "Anthropic",
    emoji: "🧠",
    shortLabel: "C",
    color: "#d97706",
    traits: {
      writing: 9,
      coding: 9,
      image_gen: 0,
      image_understanding: 8,
      speed: 7,
      cost: 6,
      reasoning: 9,
      long_context: 9,
      multimodal: 7,
      open_source: 0,
      ecosystem: 7,
    },
    bestFor: [
      "thoughtful writing",
      "long documents",
      "careful reasoning",
      "code architecture",
    ],
    watchOuts: [
      "no image generation",
      "not the cheapest option",
    ],
    tagline: "The careful thinker with great taste in prose.",
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    org: "OpenAI",
    emoji: "⚡",
    shortLabel: "4o",
    color: "#10a37f",
    traits: {
      writing: 7,
      coding: 8,
      image_gen: 7,
      image_understanding: 8,
      speed: 8,
      cost: 6,
      reasoning: 8,
      long_context: 7,
      multimodal: 9,
      open_source: 0,
      ecosystem: 9,
    },
    bestFor: [
      "all-around tasks",
      "tool integrations",
      "multimodal work",
      "fast iteration",
    ],
    watchOuts: [
      "writing can feel generic",
      "not open source",
    ],
    tagline: "The Swiss Army knife. Does everything pretty well.",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    org: "OpenAI",
    emoji: "🏎️",
    shortLabel: "mini",
    color: "#10a37f",
    traits: {
      writing: 5,
      coding: 6,
      image_gen: 0,
      image_understanding: 6,
      speed: 9,
      cost: 9,
      reasoning: 5,
      long_context: 6,
      multimodal: 6,
      open_source: 0,
      ecosystem: 9,
    },
    bestFor: [
      "high-volume tasks",
      "quick classification",
      "budget-friendly apps",
    ],
    watchOuts: [
      "weaker reasoning",
      "less nuanced writing",
    ],
    tagline: "Cheap, fast, and good enough for most things.",
  },
  {
    id: "o3",
    name: "o3",
    org: "OpenAI",
    emoji: "🔬",
    shortLabel: "o3",
    color: "#10a37f",
    traits: {
      writing: 6,
      coding: 9,
      image_gen: 0,
      image_understanding: 7,
      speed: 3,
      cost: 3,
      reasoning: 10,
      long_context: 7,
      multimodal: 5,
      open_source: 0,
      ecosystem: 8,
    },
    bestFor: [
      "hard math and logic",
      "complex code problems",
      "deep analysis",
    ],
    watchOuts: [
      "slow and expensive",
      "overkill for simple tasks",
      "writing is functional, not stylish",
    ],
    tagline: "The heavyweight thinker. Bring your hard problems.",
  },
  {
    id: "gemini-pro",
    name: "Gemini 2.5 Pro",
    org: "Google",
    emoji: "💎",
    shortLabel: "GP",
    color: "#4285f4",
    traits: {
      writing: 7,
      coding: 8,
      image_gen: 7,
      image_understanding: 9,
      speed: 6,
      cost: 5,
      reasoning: 9,
      long_context: 10,
      multimodal: 9,
      open_source: 0,
      ecosystem: 7,
    },
    bestFor: [
      "massive documents",
      "video understanding",
      "multimodal analysis",
      "Google ecosystem",
    ],
    watchOuts: [
      "writing style less distinctive",
      "occasional hallucination",
    ],
    tagline: "The context monster. Feed it your whole codebase.",
  },
  {
    id: "gemini-flash",
    name: "Gemini 2.5 Flash",
    org: "Google",
    emoji: "✨",
    shortLabel: "GF",
    color: "#4285f4",
    traits: {
      writing: 6,
      coding: 7,
      image_gen: 0,
      image_understanding: 7,
      speed: 9,
      cost: 9,
      reasoning: 7,
      long_context: 9,
      multimodal: 8,
      open_source: 0,
      ecosystem: 7,
    },
    bestFor: [
      "fast multimodal tasks",
      "large context on a budget",
      "quick prototyping",
    ],
    watchOuts: [
      "less capable on hard reasoning",
      "no image generation",
    ],
    tagline: "Fast, cheap, and surprisingly capable.",
  },
  {
    id: "llama-70b",
    name: "Llama 3.3 70B",
    org: "Meta",
    emoji: "🦙",
    shortLabel: "LL",
    color: "#0668e1",
    traits: {
      writing: 6,
      coding: 7,
      image_gen: 0,
      image_understanding: 0,
      speed: 7,
      cost: 9,
      reasoning: 7,
      long_context: 6,
      multimodal: 0,
      open_source: 10,
      ecosystem: 5,
    },
    bestFor: [
      "self-hosting",
      "privacy-sensitive work",
      "budget deployments",
      "open-source projects",
    ],
    watchOuts: [
      "no image capabilities",
      "requires own infrastructure",
      "smaller community tools",
    ],
    tagline: "Open source champion. Your data stays yours.",
  },
  {
    id: "mistral-large",
    name: "Mistral Large",
    org: "Mistral",
    emoji: "🌊",
    shortLabel: "ML",
    color: "#ff7000",
    traits: {
      writing: 7,
      coding: 7,
      image_gen: 0,
      image_understanding: 6,
      speed: 7,
      cost: 7,
      reasoning: 7,
      long_context: 6,
      multimodal: 5,
      open_source: 8,
      ecosystem: 5,
    },
    bestFor: [
      "European data residency",
      "multilingual work",
      "balanced open-source option",
    ],
    watchOuts: [
      "smaller ecosystem",
      "less battle-tested than top tier",
    ],
    tagline: "The European contender. Solid all-around.",
  },
  {
    id: "midjourney",
    name: "Midjourney",
    org: "Midjourney",
    emoji: "🎨",
    shortLabel: "MJ",
    color: "#e84393",
    traits: {
      writing: 0,
      coding: 0,
      image_gen: 10,
      image_understanding: 0,
      speed: 6,
      cost: 5,
      reasoning: 0,
      long_context: 0,
      multimodal: 3,
      open_source: 0,
      ecosystem: 4,
    },
    bestFor: [
      "stunning visuals",
      "creative direction",
      "artistic imagery",
      "product photography style",
    ],
    watchOuts: [
      "text-only tasks? wrong tool",
      "Discord-based workflow",
      "subscription required",
    ],
    tagline: "The artist. Don't ask it to write code.",
  },
  {
    id: "dall-e-3",
    name: "DALL-E 3",
    org: "OpenAI",
    emoji: "🖼️",
    shortLabel: "DE",
    color: "#10a37f",
    traits: {
      writing: 0,
      coding: 0,
      image_gen: 8,
      image_understanding: 0,
      speed: 7,
      cost: 6,
      reasoning: 0,
      long_context: 0,
      multimodal: 4,
      open_source: 0,
      ecosystem: 9,
    },
    bestFor: [
      "quick image generation",
      "text in images",
      "ChatGPT integration",
    ],
    watchOuts: [
      "less artistic control than Midjourney",
      "style can feel samey",
    ],
    tagline: "Easy image gen inside the OpenAI world.",
  },
  {
    id: "flux-pro",
    name: "Flux Pro",
    org: "Black Forest Labs",
    emoji: "🔥",
    shortLabel: "FX",
    color: "#ff4500",
    traits: {
      writing: 0,
      coding: 0,
      image_gen: 9,
      image_understanding: 0,
      speed: 7,
      cost: 6,
      reasoning: 0,
      long_context: 0,
      multimodal: 3,
      open_source: 7,
      ecosystem: 4,
    },
    bestFor: [
      "high-quality image generation",
      "photorealistic outputs",
      "open-weight option",
    ],
    watchOuts: [
      "newer, less documented",
      "smaller community",
    ],
    tagline: "The new hotness in image gen. Punches up.",
  },
  {
    id: "claude-haiku",
    name: "Claude Haiku",
    org: "Anthropic",
    emoji: "🍃",
    shortLabel: "CH",
    color: "#d97706",
    traits: {
      writing: 6,
      coding: 7,
      image_gen: 0,
      image_understanding: 6,
      speed: 9,
      cost: 9,
      reasoning: 6,
      long_context: 7,
      multimodal: 5,
      open_source: 0,
      ecosystem: 7,
    },
    bestFor: [
      "high-volume processing",
      "quick classification",
      "budget API usage",
      "real-time features",
    ],
    watchOuts: [
      "less nuanced than full Claude",
      "weaker on hard reasoning",
    ],
    tagline: "Claude's fast little sibling. Great bang for buck.",
  },
];
